language: shell
dist: bionic
os:
  - linux
arch:
  - amd64
services:
  - docker
env:
# https://itnext.io/how-to-run-parallel-tests-on-travis-ci-with-build-matrix-feature-4771a9e1af63
  matrix:
    - BEATS_VERSION=7.4.2 BEATS=filebeat
    - BEATS_VERSION=7.5.2 BEATS=filebeat
    - BEATS_VERSION=7.6.1 BEATS=filebeat
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - IMAGE_NAME="$DOCKER_USERNAME"
    - BUILDER_IMAGE="andig/beats4pi"
    - GOARM=7
    - GOARCH=arm

before_script:
  - docker version
  - export TAG="$BEATS_VERSION-$GORACHv$GOARM"
  - export IMAGE="$IMAGE_NAME/$BEATS:$TAG"
  - docker pull "$IMAGE" || true

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker run --rm -v $(pwd):/build -e BEATS=$BEATS -e BEATS_VERSION=$BEATS_VERSION -e GOARM=$GOARM -e GOARCH=$GOARCH $BUILDER_IMAGE
  - ls -lah
  - tar -xvzf "filebeat-$BEATS_VERSION-linux-arm7.tar.gz"
  - export TAG="$BEATS_VERSION-$GORACHv$GOARM"
  - export IMAGE="$IMAGE_NAME/$BEATS:$TAG"
  - echo "$IMAGE"
  - docker build --build-arg BEATS_VERSION="$BEATS_VERSION" --tag "$IMAGE" .
  - docker push "$IMAGE"

after_script:
  - docker images

branches:
  only:
    - master
